# Generated by Django 5.0.2 on 2024-02-10 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("render", "0002_choice_question_delete_render_choice_question"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Question",
            new_name="Render",
        ),
    ]
